

```{r get enrollment by cycle}
#| echo: false
#| eval: !expr params$enrollment_by_cycle
#| results: asis

abcdsReporter:::format_quarto("Enrollment by Cycle", "subsection")

enrollment <- abcdsReporter::get_registry(
  examdate,
  apply_labels = TRUE
)

enrollment$event_label <- gsub(
  " - Month [0-9]{1,2}",
  "",
  enrollment$event_label
)

enrollment_tbl <- enrollment %>%
  dplyr::mutate(
    Year = format(as.Date(examdate), "%Y"),
    Year = ifelse(is.na(Year), "Missing Exam Date", Year)
  ) %>%
  dplyr::group_by(Year) %>%
  dplyr::count(event_label) %>%
  tidyr::pivot_wider(
    names_from = event_label,
    values_from = n,
    values_fill = 0
  )

data.frame(
  Year = "Total",
  Cycle = unique(enrollment$event_label),
  Value = colSums(enrollment_tbl[2:4])
) %>%
  tidyr::pivot_wider(names_from = Cycle, values_from = Value) %>%
  rbind(enrollment_tbl, .) %>%
  flextable::flextable() %>%
  abcdsReporter:::ft_add_abcds_theme() %>%
  flextable::width(j = 1, width = 2.25) %>%
  flextable::width(j = 2:4, width = 1)

abcdsReporter:::format_quarto(type = "newpage")

```


```{r retreiving demographics from atri}
#| echo: false
#| eval: !expr params$demographics
#| results: asis

abcdsReporter:::format_quarto("Demographics", "subsection")

demographics <- abcdsReporter::get_demographics(
  age_at_visit,
  de_race,
  de_gender,
  de_ethnicity,
  site = NULL,
  cycle = NULL,
  apply_labels = TRUE
)

demographics %>%
  dplyr::mutate(de_race = NA) %>%
  dplyr::select(
    age_at_visit,
    de_gender,
    de_ethnicity,
    de_race,
    `White `:`Native Hawaiian/Other Pacific Islander`
  ) %>%
  dplyr::mutate(
    de_gender = forcats::fct_drop(de_gender),
    de_ethnicity = forcats::fct_drop(de_ethnicity),
    de_race = "",
  ) %>%
  gtsummary::tbl_summary(
    missing = "no",
    label = list(age_at_visit ~ "Age (Years)", de_race = "Race"),
    statistic = list(gtsummary::all_continuous() ~ "{mean} ± {sd}"),
    digits = list(gtsummary::all_continuous() ~ 1)
  ) %>%
  gtsummary::as_tibble() %>%
  dplyr::filter(.[[1]] != "") %>%
  flextable::flextable() %>%
  flextable::set_header_labels(
    values = c("Variable", paste0("N = ", nrow(demographics)))
  ) %>%
  abcdsReporter:::ft_add_abcds_theme() %>%
  flextable::bold(i = c(1:2, 5:6), j = 1) %>%
  flextable::width(j = 1, width = 4) %>%
  flextable::width(j = 2, width = 1.5)

abcdsReporter:::format_quarto(type = "newpage")

```


