```{r getting imaging metadata from atri and loni for completed scans}
#| echo: false
#| eval: !expr (params$imaging_scan_counts) | (params$imaging_scan_counts_by_site)
#| results: asis

imaging_map <-
  tibble::tribble(
    ~atri_scan_names , ~loni_scan_names , ~scan_labels       ,
    "amymeta"        , "amy"            , "Amyloid PET Scan" ,
    "taumeta"        , "tau"            , "Tau PET Scan"     ,
    "mrimeta"        , "mri"            , "MRI Imaging"      ,
    "fdgmeta"        , "fdg"            , "FDG PET Scan"     ,
  )

atri_imaging <-
  purrr::map(imaging_map[["atri_scan_names"]], .f = function(x) {
    img <- abcdsReporter::get_imaging(done, imaging = x)
    img$done <- as.numeric(img$done)
    doneindx <- which(colnames(img) == "done")
    colnames(img)[doneindx] <- paste0(gsub("meta", "", x), "_done")
    return(img)
  })

id_vars <- abcdsReporter:::get_ids(atri_imaging[[1]])
atri_imaging <- purrr::reduce(atri_imaging, dplyr::full_join, by = id_vars)
atri_imaging$ids <- atri_imaging$subject_label


if (!is.null(params$lonidir)) {
  loni_imaging <- purrr::map(
    imaging_map[["loni_scan_names"]],
    .f = function(x) {
      img <- abcds::read_imaging(person = "participants", scan = x)
      img <- img[, c("subject_label", "event_sequence", paste0(x, "_done"))]
      return(img)
    }
  )

  loni_imaging <- purrr::reduce(
    loni_imaging,
    dplyr::full_join,
    by = c("subject_label", "event_sequence")
  )

  atri_imaging <- abcdsReporter:::loni_join(
    atri_data = atri_imaging,
    loni_data = loni_imaging,
    variables = paste0(imaging_map[["loni_scan_names"]], "_done")
  )
}

```


```{r displaying table for imaging scans}
#| echo: false
#| eval: !expr params$imaging_scan_counts
#| results: asis

abcdsReporter:::format_quarto("Imaging Type by Number of Scans", "subsection")

imaging_scan_counts <- abcdsReporter::multiple_count_by(
  data = atri_imaging,
  names = paste0(imaging_map[["loni_scan_names"]], "_done"),
  labels = imaging_map[["scan_labels"]],
  ids = "ids",
  varname = "Imaging Scan"
)

imgtime <- as.numeric(colnames(imaging_scan_counts)[
  2:ncol(imaging_scan_counts)
])

imaging_scan_counts_footnote <- paste(
  glue::glue("Numbers {min(imgtime)} to {max(imgtime)}"),
  "show how many participants completed at least that many scans."
)

imaging_scan_counts %>%
  flextable::flextable() %>%
  abcdsReporter:::ft_add_abcds_theme() %>%
  flextable::add_footer_row(
    values = imaging_scan_counts_footnote,
    colwidths = ncol(imaging_scan_counts)
  ) %>%
  flextable::width(j = 1, width = 2) %>%
  flextable::width(j = 2:(max(imgtime) + 1), width = 3 / max(imgtime))

abcdsReporter:::format_quarto(type = "newpage")

```

```{r getting mri sequence data from atri and loni for completed scans}
#| echo: false
#| eval: !expr params$mri_sequence_counts
#| results: asis

abcdsReporter:::format_quarto("MRI Sequences by Number of Scans", "subsection")

atri_mri_imaging <- abcdsReporter::get_mri_sequences(name = "description")
atri_mri_imaging$ids <- atri_mri_imaging$subject_label

if (!is.null(params$lonidir)) {
  loni_mri_imaging <- abcds::read_imaging(person = "participants", scan = "mri")

  loni_mri_imaging <- loni_mri_imaging[, c(
    "subject_label",
    "event_sequence",
    "mri_done",
    "mrseqs"
  )]
  loni_mri_imaging <- abcds::apply_factor_labels(loni_mri_imaging)

  mri_columns <- c(
    "mri_done",
    "mrseqs",
    abcdsReporter:::.mri_sequence_key[["description"]]
  )

  atri_mri_imaging <- abcdsReporter:::loni_join(
    atri_data = atri_mri_imaging,
    loni_data = loni_mri_imaging,
    variables = mri_columns
  )
}

mri_sequences <- abcdsReporter::multiple_count_by(
  data = atri_mri_imaging,
  names = abcdsReporter:::.mri_sequence_key[["description"]],
  labels = abcdsReporter:::.mri_sequence_key[["abbreviation"]],
  ids = "ids",
  varname = "MRI Sequence"
)

mritime <- as.numeric(colnames(mri_sequences)[
  2:ncol(mri_sequences)
])

mri_sequences_footnote <- paste(
  glue::glue("Numbers {min(mritime)} to {max(mritime)}"),
  "show how many participants completed at least that many sequences."
)

mri_sequences %>%
  flextable::flextable() %>%
  abcdsReporter:::ft_add_abcds_theme() %>%
  flextable::add_footer_row(
    values = mri_sequences_footnote,
    colwidths = ncol(mri_sequences)
  ) %>%
  flextable::width(j = 1, width = 1.5) %>%
  flextable::width(j = 2:(max(mritime) + 1), width = 3.5 / max(mritime))

abcdsReporter:::format_quarto(type = "newpage")

```



```{r  displaying table for imaging scans by site}
#| echo: false
#| eval: !expr params$imaging_scan_counts_by_site
#| results: asis

abcdsReporter:::format_quarto("Amyloid PET Scans by Site", "subsection")

atri_imaging <-
  purrr::map(imaging_map[["atri_scan_names"]], .f = function(x) {
    img <- abcdsReporter::get_imaging(done, imaging = x)
    img$done <- as.numeric(img$done)
    doneindx <- which(colnames(img) == "done")
    colnames(img)[doneindx] <- paste0(gsub("meta", "", x), "_done")
    return(img)
  })

id_vars <- abcdsReporter:::get_ids(atri_imaging[[1]])
atri_imaging <- purrr::reduce(atri_imaging, dplyr::full_join, by = id_vars)
atri_imaging$ids <- atri_imaging$subject_label


atri_imaging %>%
  dplyr::count(Site = site_label, event_code, done = amy_done) %>%
  dplyr::filter(done == 1) %>%
  dplyr::mutate(
    event_code = factor(
      event_code,
      levels = c("cyc1", "cyc2", "cyc3"),
      labels = c("Cycle 1\n", "Cycle 2\n", "Cycle 3\n")
    )
  ) %>%
  tidyr::pivot_wider(
    id_cols = Site,
    names_from = event_code,
    values_from = n,
    values_fill = 0
  ) %>%
  dplyr::arrange(Site) %>%
  flextable::flextable() %>%
  abcdsReporter:::ft_add_abcds_theme() %>%
  flextable::width(j = 1, width = 3) %>%
  flextable::width(j = 2:4, width = 2.25 / 3)

abcdsReporter:::format_quarto(type = "newpage")

```


```{r}

# lonidir <- '/Users/bhelsel/Desktop/Data/ABCDS LONI DATA'

# list.files(lonidir, "MRI", full.names = TRUE)
# loni_mri <- grepl()

# mri <- get_imaging(done, mrseqs, apply_labels = TRUE, imaging = "mrimeta")

# get_codebook(abcds, mrimeta)

```